Repository hmcts/pre-shared-infrastructure, pull requests merged in 2023-11, with the labels that each got.

#634 S28-1954 set sbox resources to expire after 30 days
  .terraform-version
  Jenkinsfile_CNP
  provider.tf
Labels: destroy

#639 S28-1954 set sbox resources to expire after 30 days
  .terraform-version
  Jenkinsfile_CNP
  provider.tf
Labels: destroy

#640 S28-1978 Add metric alerts
  Jenkinsfile_CNP
  main.tf
  postgres.tf
  sa-final.tf
  sa-ingest.tf
Labels: add-or-update

#644 S28-2161 Downsize edit vms
  vm-edit.tf
Labels: destroy

#643 S28-1978 Add metric alerts
  Jenkinsfile_CNP
  main.tf
  postgres.tf
  sa-final.tf
  sa-ingest.tf
  vm-edit.tf
Labels: add-or-update

#646 Add app insights instrumentation key
  main.tf
Labels: no-changes

#649 Store the db FQDN in KV for app to consume
  postgres.tf
Labels: add-or-update

#650 Add app insights instrumentation key to key vault
  main.tf
Labels: no-changes

#651 Add a new db for the api to use
  postgres.tf
Labels: add-or-update

#652 Add a non-prod fake AppInsights key for lower envs
  main.tf
Labels: add-or-update

#655 S28-1954 Refactor and remove automation account
  apim.tf
  data.tf
  demo.tfvars
  dev.tfvars
  main.tf
  prod.tfvars
  sbox.tfvars
  stg.tfvars
  test.tfvars
  variables.tf
Labels: add-or-update

#656 S28-2181 clean up AD group perms
  data.tf
  variables.tf
Labels: destroy

#658 Use platops naming convention for db credentials
  postgres.tf
Labels: add-or-update

#659 Amend team perms
  vm-edit.tf
Labels: destroy

#661 Removes APIM Integration
  README.md
  apim.tf
  data.tf
Labels: destroy

#662 Sync changes with lower envs
  Jenkinsfile_CNP
Labels: no-changes

#660 Integrate PRE API with central APIm instance
  apim.tf
  data.tf
Labels: add-or-update
