Repository hmcts/pre-shared-infrastructure, pull requests merged in 2024-03, with the labels that each got.

#730 Use govuk design template for password reset page
  b2c/custom_policies/TrustFrameworkExtensions.xml
Labels: no-changes

#732 Missed this class for B2C body
  b2c/main.css
Labels: destroy

#733 Add 2fa to b2c
  b2c/custom_policies/TrustFrameworkBase.xml
Labels: no-changes

#735 Update TrustFrameworkBase.xml
  b2c/custom_policies/TrustFrameworkBase.xml
Labels: no-changes

#736 Add MFA to B2C
  .github/workflows/b2c_custom_policies.yml
  b2c/custom_policies/TrustFrameworkBase.xml
Labels: add-or-update

#740 Use precompiled gds frontend and fix b2c styling
  b2c/assets/copyright.png
  b2c/assets/login.html
  b2c/assets/logo_gov.png
  b2c/assets/main.css
  b2c/assets/mfa.css
  b2c/assets/mfa.html
  b2c/custom_policies/TrustFrameworkExtensions.xml
  b2c/views/assets/fonts/bold-affa96571d-v2.woff
  b2c/views/assets/fonts/bold-b542beb274-v2.woff2
  b2c/views/assets/fonts/light-94a07e06a1-v2.woff2
  b2c/views/assets/fonts/light-f591b13f7d-v2.woff
  b2c/views/assets/images/favicon.ico
  b2c/views/assets/images/favicon.svg
  b2c/views/assets/images/govuk-crest-2x.png
  b2c/views/assets/images/govuk-crest.png
  b2c/views/assets/images/govuk-icon-180.png
  b2c/views/assets/images/govuk-icon-192.png
  b2c/views/assets/images/govuk-icon-512.png
  b2c/views/assets/images/govuk-icon-mask.svg
  b2c/views/assets/images/govuk-opengraph-image.png
  b2c/views/assets/manifest.json
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/govuk-frontend-5.2.0.min.css.map
  b2c/views/css/main.css
  b2c/views/js/govuk-frontend-5.2.0.min.js
  b2c/views/js/govuk-frontend-5.2.0.min.js.map
  b2c/views/template.html
  main.tf
  sa-sa.tf
Labels: destroy

#741 fix: add temp content to main.css
  b2c/views/css/main.css
Labels: add-or-update

#742 fix: override b2c styles
  b2c/custom_policies/TrustFrameworkExtensions.xml
  b2c/views/css/main.css
  b2c/views/template.html
Labels: destroy

#739 Limits signups to set number of email tlds
  b2c/custom_policies/SignUpOrSignin.xml
Labels: no-changes

#743 fix: urls and add back js
  b2c/b2c_injection_reference/forgot_password.html
  b2c/b2c_injection_reference/login.html
  b2c/b2c_injection_reference/mfa.html
  b2c/b2c_injection_reference/register.html
  b2c/views/css/main.css
  b2c/views/template.html
  main.tf
Labels: destroy

#744 Fix/styling
  b2c/views/css/main.css
Labels: destroy

#745 S28 2444/tsandcs
  b2c/b2c_injection_reference/register.html
  b2c/custom_policies/SignUpOrSignin.xml
  b2c/custom_policies/TrustFrameworkBase.xml
  b2c/views/css/main.css
  b2c/views/template.html
Labels: destroy

#746 Adds link to terms and conditions page
  b2c/views/template.html
Labels: destroy

#747 Fix blank page on B2C
  b2c/custom_policies/SignUpOrSignin.xml
  b2c/views/template.html
Labels: destroy

#748 use template for error page
  b2c/custom_policies/TrustFrameworkExtensions.xml
Labels: no-changes

#749 Forgotten Login sub journey
  .github/workflows/b2c_custom_policies.yml
  b2c/b2c_injection_reference/verify-password-reset-code.html
  b2c/custom_policies/PasswordReset.xml
  b2c/custom_policies/SignUpOrSignin.xml
  b2c/custom_policies/TrustFrameworkBase.xml
  b2c/custom_policies/TrustFrameworkExtensions.xml
  b2c/views/css/main.css
Labels: destroy

#751 Style tweaks
  b2c/b2c_injection_reference/mfa-resend.html
  b2c/views/css/main.css
  b2c/views/template.html
Labels: destroy

#753 Move js to external file
  b2c/views/js/b2c.js
  b2c/views/template.html
  main.tf
Labels: destroy

#754 Forgot to set this
  b2c/views/template.html
Labels: destroy

#757 Set a content-type for js files juploaded to b2c SA
  main.tf
  sa-sa.tf
Labels: add-or-update

#762 Add sa CORS rules per b2c environment
  sa-sa.tf
Labels: add-or-update

#765 Allow solirius and hmail emails on lower envs
  b2c/custom_policies/demo/SignUpOrSignin.xml
  b2c/custom_policies/dev/SignUpOrSignin.xml
  b2c/custom_policies/prod/SignUpOrSignin.xml
  b2c/custom_policies/stg/SignUpOrSignin.xml
  b2c/custom_policies/test/SignUpOrSignin.xml
Labels: no-changes

#767 B2c cancel button
  b2c/custom_policies/demo/TrustFrameworkBase.xml
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/dev/TrustFrameworkBase.xml
  b2c/custom_policies/dev/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkBase.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/custom_policies/stg/TrustFrameworkBase.xml
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
  b2c/custom_policies/test/TrustFrameworkBase.xml
  b2c/custom_policies/test/TrustFrameworkExtensions.xml
Labels: no-changes

#768 S28-2666/forgotten password journey broken
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/dev/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
  b2c/custom_policies/test/TrustFrameworkExtensions.xml
  b2c/views/css/main.css
Labels: destroy

#770 S28 2673/double email verify
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/dev/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
  b2c/custom_policies/test/TrustFrameworkExtensions.xml
Labels: no-changes

#771 Document B2C setup
  b2c/README.md
Labels: add-or-update

#772 Fix poor claim verification error message
  b2c/custom_policies/demo/TrustFrameworkLocalization.xml
  b2c/custom_policies/dev/TrustFrameworkLocalization.xml
  b2c/custom_policies/prod/TrustFrameworkLocalization.xml
  b2c/custom_policies/stg/TrustFrameworkLocalization.xml
  b2c/custom_policies/test/TrustFrameworkLocalization.xml
Labels: no-changes

#774 Show password criteria on b2c login and reset password pages
  b2c/b2c_injection_reference/forgot_password.html
  b2c/b2c_injection_reference/register.html
  b2c/views/js/b2c.js
Labels: destroy

#775 Update b2c_custom_policies.yml
  .github/workflows/b2c_custom_policies.yml
Labels: no-changes

#776 Fix demo custom policy to use the right ids
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
Labels: add-or-update

#779 Fix prod custom policy to use the right ids
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
Labels: add-or-update

#780 Re-add overwritten changes
  README.md
  b2c-templates.tf
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/main.css
  b2c/views/template.html
  sa-sa.tf
Labels: destroy

#781 S28-2729 Template B2C views
  README.md
  b2c-templates.tf
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/main.css
  b2c/views/template.html
  sa-sa.tf
Labels: destroy

#783 Demo
  README.md
  b2c-templates.tf
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/main.css
  b2c/views/js/b2c.js
  b2c/views/template.html
  sa-sa.tf
Labels: destroy

#787 S28-2729 Template B2C views
  README.md
  b2c-templates.tf
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/main.css
  b2c/views/js/b2c.js
  b2c/views/template.html
  sa-sa.tf
Labels: destroy

#782 B2C remove 16 character limit on password length
  b2c/b2c_injection_reference/forgot_password.html
  b2c/b2c_injection_reference/register.html
  b2c/custom_policies/demo/TrustFrameworkBase.xml
  b2c/custom_policies/demo/TrustFrameworkLocalization.xml
  b2c/custom_policies/dev/TrustFrameworkBase.xml
  b2c/custom_policies/dev/TrustFrameworkLocalization.xml
  b2c/custom_policies/prod/TrustFrameworkBase.xml
  b2c/custom_policies/prod/TrustFrameworkLocalization.xml
  b2c/custom_policies/stg/TrustFrameworkBase.xml
  b2c/custom_policies/stg/TrustFrameworkLocalization.xml
  b2c/custom_policies/test/TrustFrameworkBase.xml
  b2c/custom_policies/test/TrustFrameworkLocalization.xml
Labels: add-or-update

#788 Amend password policy
  b2c/custom_policies/dev/TrustFrameworkBase.xml
  b2c/custom_policies/prod/TrustFrameworkBase.xml
  b2c/custom_policies/stg/TrustFrameworkBase.xml
  b2c/custom_policies/test/TrustFrameworkBase.xml
Labels: add-or-update

#789 Fix B2C 'weak' regex policy error
  b2c/b2c_injection_reference/forgot_password.html
  b2c/b2c_injection_reference/register.html
  b2c/custom_policies/demo/TrustFrameworkBase.xml
  b2c/custom_policies/dev/TrustFrameworkBase.xml
  b2c/custom_policies/prod/TrustFrameworkBase.xml
  b2c/custom_policies/stg/TrustFrameworkBase.xml
  b2c/custom_policies/test/TrustFrameworkBase.xml
Labels: add-or-update

#790 Amend password policy for dev, test, demo
  b2c/custom_policies/demo/TrustFrameworkBase.xml
  b2c/custom_policies/dev/TrustFrameworkBase.xml
  b2c/custom_policies/test/TrustFrameworkBase.xml
Labels: add-or-update
