Repository hmcts/pre-shared-infrastructure, pull requests merged in 2024-05, with the labels that each got.

#797 Make the whole email case insensitive in B2C
  b2c/views/js/b2c.js
Labels: stg/add-or-update, prod/add-or-update

#796 Remove data gateways in lower environmnents
  vm-datagateway.tf
Labels: stg/add-or-update

#800 Fix blob not updating
  b2c-templates.tf
  b2c/views/css/govuk-frontend-5.2.0.min.css
  b2c/views/css/main.css
  b2c/views/js/b2c.js
  b2c/views/template.html
  main.tf
  sa-sa.tf
Labels: stg/destroy, prod/destroy

#801 Fix blob paths
  b2c-templates.tf
  sa-sa.tf
Labels: stg/destroy, prod/destroy

#802 Fix blob paths
  b2c-templates.tf
Labels: stg/destroy, prod/destroy

#803 Revert "Fix blob paths"
  b2c-templates.tf
Labels: stg/destroy, prod/destroy

#805 Fix template path
  b2c-templates.tf
  b2c/views/js/b2c.js
  b2c/views/template.html
Labels: stg/destroy, prod/destroy

#807 correct
  b2c-templates.tf
Labels: stg/destroy, prod/destroy

#819 Preview
  b2c-templates.tf
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/dev/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
  b2c/custom_policies/test/TrustFrameworkExtensions.xml
  b2c/views/html/template.html
  b2c/views/js/b2c.js
  sa-sa.tf
Labels: stg/destroy, test/destroy

#821 Fix b2c regex for cjsm.net emails
  b2c/b2c_injection_reference/register.html
  b2c/b2c_injection_reference/verify-password-reset-code.html
  b2c/custom_policies/demo/SignUpOrSignin.xml
  b2c/custom_policies/dev/SignUpOrSignin.xml
  b2c/custom_policies/prod/SignUpOrSignin.xml
  b2c/custom_policies/stg/SignUpOrSignin.xml
  b2c/custom_policies/test/SignUpOrSignin.xml
Labels: stg/add-or-update, prod/destroy

#823 S28-2907 B2C Templating Fix
  b2c-templates.tf
  b2c/custom_policies/demo/TrustFrameworkExtensions.xml
  b2c/custom_policies/dev/TrustFrameworkExtensions.xml
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
  b2c/custom_policies/test/TrustFrameworkExtensions.xml
  b2c/views/html/template.html
  b2c/views/js/b2c.js
  sa-sa.tf
Labels: stg/destroy, prod/destroy
