Repository hmcts/pre-shared-infrastructure, pull requests merged in 2024-02, with the labels that each got.

#709 Update gitignore, editorconfig, readme
  .editorconfig
  .gitignore
  README.md
Labels: add-or-update

#712 Update main.tf
  main.tf
Labels: add-or-update

#713 Amend references to app insights module
  main.tf
Labels: no-changes

#714 Add a container for b2c blobs
  sa-sa.tf
Labels: add-or-update

#715 Amend container access for b2c
  main.tf
  sa-sa.tf
Labels: destroy

#716 Add b2c files to container
  main.tf
  sa-sa.tf
  variables.tf
Labels: add-or-update

#717 Add app insights key in non-prod
  main.tf
Labels: destroy

#710 Ignore db pw changes for now
  postgres.tf
Labels: no-changes

#718 Modify title in b2c login page
  b2c/login.html
Labels: destroy

#719 Amend b2c css
  b2c/login.css
Labels: destroy

#720 Add B2C custom policies
  .github/workflows/b2c_custom_policies.yml
  b2c/custom_policies/PasswordReset.xml
  b2c/custom_policies/ProfileEdit.xml
  b2c/custom_policies/SignUpOrSignin.xml
  b2c/custom_policies/TrustFrameworkBase.xml
  b2c/custom_policies/TrustFrameworkExtensions.xml
  b2c/custom_policies/TrustFrameworkLocalization.xml
Labels: no-changes

#721 update b2c_custom_policies.yml
  .github/workflows/b2c_custom_policies.yml
Labels: no-changes

#724 Add app insights connection string to non-prod envs
  main.tf
Labels: add-or-update

#725 Update TrustFrameworkExtensions.xml
  b2c/custom_policies/TrustFrameworkExtensions.xml
Labels: no-changes

#726 Call js on dom load only. Remove prod references
  b2c/custom_policies/TrustFrameworkExtensions.xml
  b2c/login.html
Labels: destroy

#728 Update html / css to match pre-portal
  b2c/bold-affa96571d-v2.woff
  b2c/bold-b542beb274-v2.woff2
  b2c/favicon.ico
  b2c/favicon.svg
  b2c/govuk-crest-2x.png
  b2c/govuk-crest.png
  b2c/govuk-icon-180.png
  b2c/govuk-icon-mask.svg
  b2c/light-94a07e06a1-v2.woff2
  b2c/light-f591b13f7d-v2.woff
  b2c/login.css
  b2c/login.html
  b2c/main.css
  sa-sa.tf
Labels: destroy

#729 Remove Private Endpoint from the B2C SA
  sa-sa.tf
Labels: destroy
