Repository hmcts/pre-shared-infrastructure, pull requests merged in 2024-09, with the labels that each got.

#897 add subnet to test also
  sa-final.tf
Labels: stg/add-or-update, prod/add-or-update

#899 Update VM edit_init type handler to 1.10.17
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#901 Set edit vm type handler version back to 1.10
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#902 use azure_monitor_type_handler_version 1.9
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#904 Update after bootstrap module changes
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#907 Remove bootstrap trigger and install hardenning requirements ourselves
  scripts/edit-init.ps1
  vm-edit.tf
Labels: stg/destroy, prod/destroy

#908 Reintroduce VM Bootstrap
  import.tf
  scripts/edit-init.ps1
  vm-edit.tf
Labels: stg/destroy, prod/destroy

#910 Pass dynatrace install flag to module
  vm-edit.tf
Labels: stg/add-or-update, prod/destroy

#906 Add action group to staging
  main.tf
Labels: stg/add-or-update, prod/add-or-update

#911 remove public access Demo, add subnet to test also
  sa-ingest.tf
Labels: stg/add-or-update, prod/add-or-update

#905 Add perf test users to B2C config to bypass 2FA
  b2c/custom_policies/stg/TrustFrameworkExtensions.xml
Labels: stg/add-or-update, prod/add-or-update

#912 Remove public access from test SAs
  sa-final.tf
  sa-ingest.tf
Labels: stg/add-or-update, prod/add-or-update

#914 Add to the VM config install_azure_monitor
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#915 azurerm 116 Update provider.tf
  provider.tf
Labels: stg/add-or-update, prod/add-or-update
