Repository hmcts/pre-shared-infrastructure, pull requests merged in 2025-10, with the labels that each got.

#1065 S28-4202 Ban shared email addresses in demo policy
  b2c/custom_policies/demo/SignUpOrSignin.xml
Labels: stg/add-or-update, prod/add-or-update

#1066 Config PRE APIm B2C app for oauth
  data.tf
  demo.tfvars
  dev.tfvars
  pre-apim-b2c.tf
  prod.tfvars
  stg.tfvars
  test.tfvars
  variables.tf
Labels: stg/destroy, prod/destroy

#1068 Grant access to B2C app
  README.md
  pre-apim-b2c.tf
Labels: stg/add-or-update, prod/destroy
