Repository hmcts/pre-shared-infrastructure, pull requests merged in 2025-04, with the labels that each got.

#976 S28-2943 Added banner to B2C login page
  b2c/views/template.html
Labels: stg/destroy, prod/destroy

#988 import tooling script stg Update stg.tfvars
  stg.tfvars
  vm-edit.tf
Labels: prod/add-or-update, stg/destroy

#989 Remove temp import
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#990 Remove ADF instance
  README.md
  azure-data-factory.tf
  prod.tfvars
  variables.tf
Labels: stg/add-or-update, prod/destroy

#991 Grant SC users contrib to voda SA whilst testing
  sa-voda.tf
Labels: stg/add-or-update, prod/destroy

#995 Explicity remove public access to VF SA...again
  sa-voda.tf
Labels: prod/add-or-update, stg/destroy

#996 Remove private endpoint for voda SA
  sa-voda.tf
Labels: stg/destroy, prod/destroy

#997 Allow public access on set ip
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#998 Match probate rules as that is what we need
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#999 Reinstate PE on voda SA
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update
