Repository hmcts/pre-shared-infrastructure, pull requests merged in 2025-05, with the labels that each got.

#1001 Revert "Remove ADF instance"
  README.md
  azure-data-factory.tf
  prod.tfvars
  variables.tf
Labels: stg/add-or-update, prod/add-or-update

#1003 Update ip access to voda SA
  sa-voda.tf
Labels: stg/add-or-update

#1004 Use branch of vm module
  vm-edit.tf
Labels: stg/add-or-update, prod/destroy

#1006 default install_splunk_uf to false to prevent second custom script install
  variables.tf
Labels: stg/add-or-update, prod/destroy

#1008 Update PRE SP name
  data.tf
Labels: stg/destroy, prod/destroy

#1009 Remove unused secret expiry date
  main.tf
  sa-final.tf
  sa-ingest.tf
  sa-sa.tf
  sa-voda.tf
  vm-edit.tf
  voda-vm.tf
Labels: stg/add-or-update, prod/add-or-update

#1011 Pre voda roles all envs
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#1012 Need data owner rather than just contributor
  sa-voda.tf
Labels: stg/destroy, prod/destroy

#1013 Enable read only access via JIT
  postgres.tf
Labels: stg/destroy, prod/destroy
