Repository hmcts/pre-shared-infrastructure, pull requests merged in 2025-06, with the labels that each got.

#1017 Add key to KV
  sa-final-backup.tf
Labels: stg/add-or-update, prod/add-or-update

#1018 Add action group to demo
  main.tf
Labels: stg/add-or-update, prod/add-or-update

#1019 Allow PRE Smoke test user to bypass 2FA
  b2c/custom_policies/prod/TrustFrameworkExtensions.xml
Labels: stg/add-or-update, prod/add-or-update

#1020 Remove sa backup no longer used.
  sa-sa-backup.tf
Labels: stg/destroy, prod/destroy

#1023 Remove ingest sa backup no longer used.
  sa-ingest-backup.tf
Labels: stg/destroy, prod/destroy

#1024 Remove vodafone VM
  prod.tfvars
  variables.tf
  voda-vm.tf
Labels: stg/add-or-update, prod/destroy

#1026 Remove final backup SA no longer used.
  sa-final-backup.tf
Labels: stg/destroy, prod/destroy
