Repository hmcts/pre-shared-infrastructure, pull requests merged in 2025-03, with the labels that each got.

#955 Create sa-voda.tf
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#958 Update storage used alert sa-voda.tf
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#957 Add Azure Data Factory to Prod
  README.md
  azure-data-factory.tf
  prod.tfvars
  variables.tf
Labels: stg/add-or-update, prod/add-or-update

#959 Add Edit VM MI to Final SA
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#962 Grant SC user contrib to final SA
  sa-final.tf
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#963 Add pre env mi to ADF
  azure-data-factory.tf
Labels: stg/add-or-update, prod/add-or-update

#964 Data reader instead of SA contributor
  sa-final.tf
  sa-ingest.tf
  sa-voda.tf
  vm-edit.tf
Labels: stg/destroy, prod/destroy

#968 Set the final SA access key as an env var on the VM
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#969 Run Mon and Tues mornings
  Jenkinsfile_CNP
Labels: stg/add-or-update, prod/add-or-update

#971 Sa key from kv
  sa-final.tf
  vm-edit.tf
Labels: stg/add-or-update, prod/add-or-update

#972 Use correct secret and force update
  variables.tf
  vm-edit.tf
Labels: stg/destroy, prod/destroy

#973 GitHub workflow to update edit vm run id
  .github/workflows/update_vm_run_id.yml
Labels: stg/add-or-update, prod/add-or-update

#974 Fix replacement in edit vm run id workflow
  .github/workflows/update_vm_run_id.yml
  variables.tf
Labels: stg/destroy, prod/destroy

#960 S28-741: Added footer link to new help page
  b2c/views/template.html
Labels: stg/destroy, prod/destroy

#975 Update edit vm run id workflow
  .github/workflows/update_vm_run_id.yml
  Jenkinsfile_SCHD
  prod.tfvars
Labels: stg/destroy, prod/destroy

#978 Bump prod VM to update
  prod.tfvars
Labels: stg/add-or-update, prod/destroy

#981 publish key to vault Update sa-voda.tf
  sa-voda.tf
Labels: stg/add-or-update, prod/add-or-update

#980 add voda VM
  prod.tfvars
  variables.tf
  voda-vm.tf
Labels: stg/destroy, prod/destroy

#983 Update voda-vm.tf
  voda-vm.tf
Labels: stg/add-or-update, prod/add-or-update

#985 add voda VM private ip
  prod.tfvars
  variables.tf
  voda-vm.tf
Labels: stg/add-or-update, prod/add-or-update
